name: thehouseofd
favicon: null
layout_spectrum: 0.5020975093357265
typography_spectrum: 0.9281597612425685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6170381570700556
  lightness: 0.3948118183761835
  saturation: 0.5202833483926952
  rhythmicContrast: 0.737739457981661
purpose: []
